stages:
  - build
  - check

.build:
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  stage: build
  script:
    - ./gradlew --warning-mode=all build
  cache:
    - key:
        files:
          - gradle/wrapper/gradle-wrapper.properties
      paths:
        - .gradle/wrapper
    - key: $CI_COMMIT_REF_SLUG
      fallback_keys:
        - master-protected
      paths:
        - .gradle/caches
  artifacts:
    when: always
    paths:
      # JUNIT test report
      - build/test-results/test/TEST-*.xml
    reports:
      junit:
        - build/test-results/test/TEST-*.xml

build:java8:
  image: eclipse-temurin:8-jdk
  extends: .build

build:java11:
  image: eclipse-temurin:11.0.27_6-jdk
  extends: .build

build:java17:
  image: eclipse-temurin:17.0.15_6-jdk
  extends: .build

build:java21:
  image: eclipse-temurin:21.0.7_6-jdk
  extends: .build

build:java24:
  image: eclipse-temurin:24-jdk
  extends: .build
